Repository AY2223S2-CS2103T-W11-4/tp, pull requests merged in 2023-04, with the labels that each got.

#326 Fix Invalid Age bug
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/model/person/Age.java
Labels: type.bug, priority.High, severity.High

#327 Bug fixes v1.4
  build.gradle
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/files/PdfReader.java
  src/main/java/seedu/address/logic/commands/DeleteFileCommand.java
  src/main/java/seedu/address/logic/commands/ViewFileCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.bug, priority.High

#329 solve bug for closing MC info window
  src/main/java/seedu/address/ui/AddMcInfo.java
  src/main/resources/view/GenerateMC.fxml
Labels: type.bug, priority.High

#330 Fix Create Command, now everything is a must
  docs/team/sfcoding123.md
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
Labels: type.bug, Must Do, priority.High, severity.High

#333 Modify DG-Design-Model part
  docs/DeveloperGuide.md
  docs/diagrams/NewModelClassDiagram.puml
  docs/images/NewModelClassDiagram.png
Labels: documentation, Must Do, priority.Medium

#334 Modify DG-Appendix-Instructions
  docs/DeveloperGuide.md
Labels: documentation, Must Do, priority.Medium

#337 Amend show hyperlink and NRIC result display due to invalid NRIC format
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Nric.java
Labels: type.bug, documentation

#338 Update PPP
  docs/team/weideteo.md
Labels: documentation

#339 Modify PPP
  docs/team/lxz333.md
Labels: documentation

#343 V1.4 bug fixes
  docs/DeveloperGuide.md
  docs/diagrams/FilesClassDiagram.puml
  docs/diagrams/createMc.puml
  docs/diagrams/uploadFile.puml
  docs/images/FilesClassDiagram.png
  docs/images/createMc.png
  docs/images/uploadFile.png
  src/main/java/seedu/address/files/ImageReader.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
Labels: documentation

#345 Update Userguide
  docs/UserGuide.md
Labels: type.bug, documentation

#346 add glossary and non-functional requirements
  docs/DeveloperGuide.md
Labels: documentation

#349 Modify DG use cases/user stories
  docs/DeveloperGuide.md
Labels: documentation

#351 Edit DG
  docs/DeveloperGuide.md
Labels: documentation

#355 Edit PPP
  docs/team/lxz333.md
Labels: documentation

#357 DG Improvement
  docs/DeveloperGuide.md
Labels: documentation

#358 DG Improvement
  docs/DeveloperGuide.md
Labels: documentation

#359 DG
  docs/DeveloperGuide.md
  docs/team/sfcoding123.md
Labels: documentation

#361 DG Improvement
  docs/DeveloperGuide.md
Labels: documentation

#365 Add links for PPP
  docs/team/lxz333.md
Labels: documentation

#366 Improved code quality
  src/main/java/seedu/address/logic/commands/ViewFileCommand.java
Labels: type.Task

#369 DG Bug
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/FilesClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/FilesClassDiagram.png
Labels: documentation

#372 Branch dg UI improve
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagramUltimate.png
  docs/team/lxz333.md
Labels: documentation

#374 Edit some links
  docs/DeveloperGuide.md
Labels: documentation
