Repository AY2223S2-CS2103T-W11-4/tp, pull requests merged in 2023-03, with the labels that each got.

#22 Edit AboutUs and Project Portfolio Page.
  docs/AboutUs.md
  docs/team/windycall.md
Labels: documentation

#40 Branch a ppp
  docs/team/lxz333.md
Labels: documentation

#41 Change of _config.yml
  docs/_config.yml
Labels: documentation

#47 DG Product Scope and User Stories
  docs/DeveloperGuide.md
Labels: documentation

#50 DG Use Cases
  docs/DeveloperGuide.md
Labels: documentation

#53 Update PPP skeleton
  docs/team/weideteo.md
Labels: documentation

#54 Add use cases
  docs/DeveloperGuide.md
Labels: documentation

#68 Branch list by name
  src/main/java/seedu/address/logic/commands/ListByNameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/PersonComparatorByName.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High, type.Story, type.Enhancement, type.Task

#78 Add a patient's medical condition
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MedicalCondition.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High, type.Story, type.Enhancement

#84 Branch list by name new
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High, type.Task

#94 Add age
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.High, type.Story

#103 List merge
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommands.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListTime.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TimeComparator.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandsTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High, type.Epic, type.Enhancement, type.Task

#98 Add test cases for add age.
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AgeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, priority.Medium

#113 List time test cases
  src/test/java/seedu/address/logic/commands/ListTimeTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonWithTime.java
Labels: priority.Medium, type.Enhancement, type.Task

#114 Add test cases for the ListByName method
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/ListByNameCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Task

#125 Added constraints for File Uploads (Ignore wrong file type)
  src/main/java/seedu/address/files/FileStorage.java
Labels: priority.High, type.Enhancement

#130 Modify the UI and add a detail displaying pane on the right
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ShowDetailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ShowDetailCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DetailDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: priority.High, type.Enhancement, type.Task

#126 V1.3 storage generate pdfs
  src/main/java/seedu/address/files/FileGenerator.java
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/files/ImageReader.java
  src/main/java/seedu/address/files/PdfReader.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/UploadFileCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
Labels: priority.High, type.Enhancement

#136 Branch a button
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/AddPersonButton.fxml
  src/main/resources/view/DetailDisplay.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Task, UI

#138 Make appointment(SearchDate command)
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/MakeAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SearchAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SearchAppointmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TimeComparator.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Epic, type.Enhancement

#137 Improved MC creation, has unique name related based on number files.
  src/main/java/seedu/address/files/FileGenerator.java
  src/main/java/seedu/address/files/FilesManager.java
  src/test/java/seedu/address/files/FileGeneratorTest.java
Labels: enhancement, priority.High, type.Enhancement

#140 add FileList to UI
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/FileCard.java
  src/main/java/seedu/address/ui/FileList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ObservableFile.java
  src/main/java/seedu/address/ui/UiFile.java
  src/main/resources/view/FileListItem.fxml
Labels: enhancement, priority.High, type.Task, UI

#143 Commented TestCase and fixed bugs for ModelManager.java constructor
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandsTest.java
Labels: type.bug, severity.VeryLow

#148 Modify DG
  docs/DeveloperGuide.md
Labels: enhancement, Must Do, priority.Medium

#149 Add a Use Case for showing the detailed information of a patient
  docs/DeveloperGuide.md
Labels: documentation

#145 integrated with Scroll Panel Ui and improved FileManager methods.
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, type.Task

#151 add view and delete button
  docs/DeveloperGuide.md
  src/main/resources/view/FileListItem.fxml
Labels: documentation, enhancement, type.Task, UI

#156 set control over upload & delete & view button
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/FileCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ObservableFile.java
  src/main/java/seedu/address/ui/UiFile.java
  src/main/resources/view/FileListItem.fxml
Labels: enhancement, priority.High, type.Enhancement, type.Task, UI

#158 Add test cases for ParseUtilTest
  src/main/java/seedu/address/model/person/MedicalCondition.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: enhancement

#159 Modified changes to Integrate with UI, added Java docs.
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/files/ImageReader.java
  src/main/java/seedu/address/files/PdfReader.java
  src/main/java/seedu/address/ui/FileCard.java
Labels: priority.High, type.Enhancement

#171 Bug fixes for View Pdf and Add Constraints for File Upload.
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/PdfReader.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: type.bug, priority.High, type.Enhancement, severity.High

#172 Appointment testcases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchAppointmentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAppointmentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchAppointmentCommandParserTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
Labels: enhancement, Must Do, priority.Medium

#177 enable update function of file list
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/FileCard.java
  src/main/java/seedu/address/ui/FileList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ObservableFile.java
  src/main/java/seedu/address/ui/UiFile.java
Labels: enhancement, priority.Medium, type.Enhancement, type.Task, UI

#175 Enhancement to generate MC class
  src/main/java/seedu/address/files/FileGenerator.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/UploadFileCommand.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/test/java/seedu/address/files/FileGeneratorTest.java
Labels: priority.High, type.Enhancement

#173 Apply Test Cases for MedicalCondition
  src/main/java/seedu/address/model/person/MedicalCondition.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/MedicalConditionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement, priority.Medium

#178 Tests for DeleteCommands
  build.gradle
  lib/Roboto/LICENSE.txt
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/files/ImageReader.java
  src/main/java/seedu/address/files/PdfReader.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/UploadFileCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandsTest.java
  src/test/java/seedu/address/logic/commands/UploadFileCommandTest.java
Labels: type.Task, severity.Medium

#179 TestCases for File Image and Pdf Reader
  src/test/java/seedu/address/files/ImageReaderTest.java
  src/test/java/seedu/address/files/PdfReaderTest.java
Labels: enhancement

#181 Revamp ADD command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: enhancement

#182 Solved bug: Main window closed after clicking
  src/main/java/seedu/address/files/ImageReader.java
Labels: type.bug, severity.High

#183 add list_name in the userguide
  docs/UserGuide.md
Labels: documentation

#184 UserGuide
  docs/UserGuide.md
Labels: documentation

#186 Revamp add version 2
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/MarkAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement

#188 Add Appointment related UserGuide.
  docs/UserGuide.md
  docs/images/screenshot_of_searchDate.png
  reports/Bernice Yu/0-mc.pdf
  reports/Charlotte Oliveiro/0-mc.pdf
  reports/Roy Balakrishnan/CS2105_Assignment_0.pdf
Labels: documentation

#190 Change userguide for NRIC
  docs/UserGuide.md
Labels: documentation, enhancement

#192 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#200 Revamp add
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: enhancement, priority.High

#201 Resolve bugs in AddAppointment
  reports/Bernice Yu/0-mc.pdf
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
Labels: enhancement, Must Do

#206 Solve Edit Testcases Bug
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.bug

#207 Complete List_Appointment
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, Must Do, priority.Medium

#208 Resolve passed appointment bugs.
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: enhancement, Must Do

#214 Branch a appointment button
  .gitignore
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/AddAppointmentWindow.java
  src/main/java/seedu/address/ui/AddPatientWindow.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/AddAppointmentWindow.fxml
  src/main/resources/view/AddPatientWindow.fxml
  src/main/resources/view/DetailDisplay.fxml
  src/main/resources/view/PersonListPanel.fxml
Labels: type.Task, UI

#211 Added new Command line operation of view {index} {index}
  src/main/java/seedu/address/files/FileGenerator.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/files/ImageReader.java
  src/main/java/seedu/address/files/PdfReader.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFileCommand.java
  src/main/java/seedu/address/logic/commands/ViewFileCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteFileCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/FileCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/files/FileGeneratorTest.java
  src/test/java/seedu/address/files/ImageReaderTest.java
  src/test/java/seedu/address/files/PdfReaderTest.java
Labels: priority.High, type.Enhancement

#217 Allow edits for medical condition, age and nric fields
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Age.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.High

#218 Minor changes to update Files and names when generate MC
  src/main/java/seedu/address/files/FilesManager.java
Labels: type.bug, severity.Medium

#222 Java docs and Style Improvement
  src/main/java/seedu/address/files/FileReader.java
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/files/PdfReader.java
Labels: enhancement, priority.High

#220 add generate window
  src/main/java/seedu/address/ui/AddMcInfo.java
  src/main/java/seedu/address/ui/DetailDisplay.java
  src/main/resources/view/DetailDisplay.fxml
  src/main/resources/view/GenerateMC.fxml
Labels: enhancement, priority.Medium, type.Task, UI

#224 solve bug for file comparator
  src/main/java/seedu/address/ui/FileComparator.java
Labels: type.bug, UI

#225 Solved bug when user Upload bad file names
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/FilesManager.java
Labels: type.bug, severity.Medium

#227 Solve Path Bug
  src/main/java/seedu/address/files/FileGenerator.java
  src/main/resources/MC.pdf
  src/main/resources/Roboto/LICENSE.txt
  src/main/resources/Roboto/Roboto-Black.ttf
  src/main/resources/Roboto/Roboto-BlackItalic.ttf
  src/main/resources/Roboto/Roboto-Bold.ttf
  src/main/resources/Roboto/Roboto-BoldItalic.ttf
  src/main/resources/Roboto/Roboto-Italic.ttf
  src/main/resources/Roboto/Roboto-Light.ttf
  src/main/resources/Roboto/Roboto-LightItalic.ttf
  src/main/resources/Roboto/Roboto-Medium.ttf
  src/main/resources/Roboto/Roboto-MediumItalic.ttf
  src/main/resources/Roboto/Roboto-Regular.ttf
  src/main/resources/Roboto/Roboto-Thin.ttf
  src/main/resources/Roboto/Roboto-ThinItalic.ttf
  src/test/java/seedu/address/files/FileGeneratorTest.java
Labels: type.bug, severity.High

#226 Branch fix appointment
  .gitignore
  src/main/java/seedu/address/ui/AddAppointmentWindow.java
Labels: UI

#229 Solve NRIC null cases bug and constraint NRIC
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.bug

#228 Added Error message for wrong File index
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/logic/commands/DeleteFileCommand.java
  src/main/java/seedu/address/logic/commands/ViewFileCommand.java
Labels: priority.High, type.Enhancement

#231 Solve bugs
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/MedicalCondition.java
  src/main/java/seedu/address/model/person/Nric.java
Labels: type.bug

#232 Added constraints for invalid days
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
Labels: type.bug, severity.High

#233 add limitation to MC duration (1-60) days
  src/main/java/seedu/address/ui/AddMcInfo.java
Labels: enhancement, UI

#234 change generate button to create
  src/main/resources/view/DetailDisplay.fxml
Labels: enhancement, UI

#235 Added feedbacks to the user
  src/main/java/seedu/address/files/FileGenerator.java
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/files/FilesManager.java
  src/test/java/seedu/address/files/FileGeneratorTest.java
Labels: priority.High, type.Enhancement, type.Task

#240 solve multiple window err
  src/main/java/seedu/address/ui/AddMcInfo.java
  src/main/java/seedu/address/ui/DetailDisplay.java
Labels: type.bug, UI

#241 solve special input bug
  src/main/java/seedu/address/ui/AddMcInfo.java
Labels: type.bug, type.Enhancement, UI

#244 Solve Bugs 2
  src/main/java/seedu/address/ui/DetailDisplay.java
Labels: type.bug, severity.High

#245 Bug Fix
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/logic/commands/UploadFileCommand.java
Labels: type.bug, Must Do, priority.High

#248 User guide and FileManagerTest case
  docs/UserGuide.md
  src/test/java/seedu/address/files/FilesManagerTest.java
Labels: documentation

#249 bug fix
  src/main/java/seedu/address/files/FileStorage.java
  src/main/java/seedu/address/ui/DetailDisplay.java
Labels: type.bug, severity.High

#259 Amend user guide
  README.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/userGuide/Add_1.png
  docs/images/userGuide/Add_2.png
  docs/images/userGuide/Appointment_1.png
  docs/images/userGuide/Appointment_2.png
  docs/images/userGuide/Create_1.png
  docs/images/userGuide/Create_2.png
  docs/images/userGuide/Ui.png
  docs/images/userGuide/Upload_1.png
  docs/images/userGuide/Upload_2.png
  docs/images/userGuide/helpMessage.png
  docs/images/userGuide/view_1.png
  docs/images/userGuide/view_2.png
  docs/index.md
Labels: documentation

#260 V1-3-DG
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/FilesClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ComponentManagers.png
  src/main/java/seedu/address/files/FileGenerator.java
  src/main/java/seedu/address/files/FileReaderManager.java
  src/main/java/seedu/address/files/Files.java
  src/main/java/seedu/address/files/FilesManager.java
  src/main/java/seedu/address/files/PdfGenerator.java
  src/main/java/seedu/address/ui/AddMcInfo.java
  src/test/java/seedu/address/files/PdfGeneratorTest.java
Labels: documentation, priority.High, type.Enhancement

#262 Modify the Ui part of DG
  .gitignore
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagramNew.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#263 Style fixes
  build.gradle
  docs/DeveloperGuide.md
  docs/images/FilesClassDiagram.png
Labels: documentation, priority.High

#264 Amend User guide
  docs/UserGuide.md
Labels: documentation

#265 improve view of delete button
  src/main/resources/view/FileListItem.fxml
Labels: type.Enhancement, UI
